language: python
install:
- pip install awscli
script:
- echo hello world
deploy:
  provider: s3
  access_key_id: "$AWS_AccessKey"
  secret_access_key: "$AWS_SecretKey"
 bucket: "divingbirdbucket"
  acl: public_read
  skip_cleanup: 'true'
